// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/auth/[auth].ts";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/signin.tsx";
import * as $6 from "./routes/signup.tsx";
import * as $7 from "./routes/supa-oauth-redirect-return.tsx";
import * as $$0 from "./islands/AuthFragmentCatcher.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/EventForm.tsx";
import * as $$3 from "./islands/SignOut.tsx";
import * as $$4 from "./islands/SignUpOrIn.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/auth/[auth].ts": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/signin.tsx": $5,
    "./routes/signup.tsx": $6,
    "./routes/supa-oauth-redirect-return.tsx": $7,
  },
  islands: {
    "./islands/AuthFragmentCatcher.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/EventForm.tsx": $$2,
    "./islands/SignOut.tsx": $$3,
    "./islands/SignUpOrIn.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
